## Feature Engineering

#### Adding following derived features:
#### aspect ratio Aspect ratio to get shape information
#### overall area of image
#### log file size for reducing skewness
#### resolution_bucket -bucketing  images based on their largest dimension to capture resolution differences without resizing

In [ ]:
%pip install albumentations --quiet

In [45]:
import boto3
import sagemaker
from sagemaker.session import Session
from sagemaker.pytorch import PyTorch
import numpy as np
from pathlib import Path
import hashlib
from pyathena import connect
import pandas as pd
import numpy as np
from datetime import datetime, timezone
from PIL import Image
import io
from sagemaker.feature_store.feature_group import FeatureGroup
import time
from time import gmtime, strftime, sleep
import albumentations as A
import os

sess = sagemaker.Session()
role = sagemaker.get_execution_role()
region = boto3.Session().region_name

s3 = boto3.client("s3")

In [2]:
%store -r bucket

In [3]:
database_name = "cat_image_analysis"
table_name = "image_landmarks_features"

s3_combined_location = (
    f"s3://{bucket}/cat-landmarks-project/processed/combined/image_landmarks_features/"
)

s3_staging_dir = f"s3://{bucket}/athena/staging/"

In [4]:
conn = connect(region_name=region, s3_staging_dir=s3_staging_dir)

In [5]:
conn = connect(
    region_name=region,
    s3_staging_dir=s3_staging_dir
)


# Create cursor
cursor = conn.cursor()

In [6]:
statement = f"""
SELECT *
FROM {database_name}.{table_name}
"""
print(statement)

df = pd.read_sql(statement, conn)
df.head(5)

SELECT *
FROM cat_image_analysis.image_landmarks_features

/tmp/ipykernel_53371/224683668.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(statement, conn)

,image_id,label,file_size,width,height,aspect_ratio,area,log_file_size,eye_center_x_norm,eye_center_y_norm,eye_dist_norm,eye_y_diff_norm,eye_angle,mouth_x_norm,mouth_y_norm,mouth_eye_y_norm,resolution_bucket,event_time,dataset_split
0,s3://sagemaker-us-east-1-567266240490/cat-land...,1,469801,375,500,0.750000,187500,13.060067,0.552,0.322000,0.170667,0.004000,0.031240,0.530667,0.398000,0.076000,None,1770528053.745045,train
1,s3://sagemaker-us-east-1-567266240490/cat-land...,1,469801,500,375,1.333333,187500,13.060067,0.249,0.297333,0.114000,0.082667,0.498117,0.206000,0.389333,0.092000,None,1770528053.745045,prod
2,s3://sagemaker-us-east-1-567266240490/cat-land...,1,469801,500,375,1.333333,187500,13.060067,0.658,0.594667,0.044000,0.005333,0.090660,0.654000,0.634667,0.040000,None,1770528053.745045,prod
3,s3://sagemaker-us-east-1-567266240490/cat-land...,1,310372,500,375,1.333333,187500,12.645530,0.409,0.477333,0.150000,0.032000,0.158655,0.382000,0.658667,0.181333,None,1770528053.745045,test
4,s3://sagemaker-us-east-1-567266240490/cat-land...,1,310372,500,333,1.501502,166500,12.645530,0.294,0.364865,0.128000,0.003003,-0.015624,0.266000,0.507508,0.142643,None,1770528053.745045,train

In [7]:
df_features = df.copy()

out_dir = Path("data/processed")
out_dir.mkdir(parents=True, exist_ok=True)

fe_path = out_dir / "image_features.parquet"
df_features.to_parquet(fe_path, index=False)

In [8]:
def resolution_bucket(row):
    max_dim = max(row["width"], row["height"])
    if max_dim < 128:
        return "small"
    elif max_dim <= 512:
        return "medium"
    else:
        return "large"

In [9]:
df_features["event_time"] = datetime.now(timezone.utc).timestamp()

np.random.seed(42)
df_features["dataset_split"] = np.random.choice(
    ["train", "val", "test", "prod"],
    size=len(df_features),
    p=[0.4, 0.1, 0.1, 0.4]
)
# Make event_time a string before writing parquet
df_features["event_time"] = df_features["event_time"].astype("string")

In [10]:
df_features.head(5)

,image_id,label,file_size,width,height,aspect_ratio,area,log_file_size,eye_center_x_norm,eye_center_y_norm,eye_dist_norm,eye_y_diff_norm,eye_angle,mouth_x_norm,mouth_y_norm,mouth_eye_y_norm,resolution_bucket,event_time,dataset_split
0,s3://sagemaker-us-east-1-567266240490/cat-land...,1,469801,375,500,0.750000,187500,13.060067,0.552,0.322000,0.170667,0.004000,0.031240,0.530667,0.398000,0.076000,None,1770529590.068841,train
1,s3://sagemaker-us-east-1-567266240490/cat-land...,1,469801,500,375,1.333333,187500,13.060067,0.249,0.297333,0.114000,0.082667,0.498117,0.206000,0.389333,0.092000,None,1770529590.068841,prod
2,s3://sagemaker-us-east-1-567266240490/cat-land...,1,469801,500,375,1.333333,187500,13.060067,0.658,0.594667,0.044000,0.005333,0.090660,0.654000,0.634667,0.040000,None,1770529590.068841,prod
3,s3://sagemaker-us-east-1-567266240490/cat-land...,1,310372,500,375,1.333333,187500,12.645530,0.409,0.477333,0.150000,0.032000,0.158655,0.382000,0.658667,0.181333,None,1770529590.068841,test
4,s3://sagemaker-us-east-1-567266240490/cat-land...,1,310372,500,333,1.501502,166500,12.645530,0.294,0.364865,0.128000,0.003003,-0.015624,0.266000,0.507508,0.142643,None,1770529590.068841,train

In [11]:
df_features.to_parquet(fe_path, index=False)

check = pd.read_parquet(fe_path)
print(check.columns.tolist())   # You should see aspect_ratio, area, log_file_size, resolution_bucket, event_time, dataset_split
check.head()

['image_id', 'label', 'file_size', 'width', 'height', 'aspect_ratio', 'area', 'log_file_size', 'eye_center_x_norm', 'eye_center_y_norm', 'eye_dist_norm', 'eye_y_diff_norm', 'eye_angle', 'mouth_x_norm', 'mouth_y_norm', 'mouth_eye_y_norm', 'resolution_bucket', 'event_time', 'dataset_split']

,image_id,label,file_size,width,height,aspect_ratio,area,log_file_size,eye_center_x_norm,eye_center_y_norm,eye_dist_norm,eye_y_diff_norm,eye_angle,mouth_x_norm,mouth_y_norm,mouth_eye_y_norm,resolution_bucket,event_time,dataset_split
0,s3://sagemaker-us-east-1-567266240490/cat-land...,1,469801,375,500,0.750000,187500,13.060067,0.552,0.322000,0.170667,0.004000,0.031240,0.530667,0.398000,0.076000,None,1770529590.068841,train
1,s3://sagemaker-us-east-1-567266240490/cat-land...,1,469801,500,375,1.333333,187500,13.060067,0.249,0.297333,0.114000,0.082667,0.498117,0.206000,0.389333,0.092000,None,1770529590.068841,prod
2,s3://sagemaker-us-east-1-567266240490/cat-land...,1,469801,500,375,1.333333,187500,13.060067,0.658,0.594667,0.044000,0.005333,0.090660,0.654000,0.634667,0.040000,None,1770529590.068841,prod
3,s3://sagemaker-us-east-1-567266240490/cat-land...,1,310372,500,375,1.333333,187500,12.645530,0.409,0.477333,0.150000,0.032000,0.158655,0.382000,0.658667,0.181333,None,1770529590.068841,test
4,s3://sagemaker-us-east-1-567266240490/cat-land...,1,310372,500,333,1.501502,166500,12.645530,0.294,0.364865,0.128000,0.003003,-0.015624,0.266000,0.507508,0.142643,None,1770529590.068841,train

In [12]:
# Using a versioned prefix so Athena reads ONLY one schema-consistent dataset
fe_s3_prefix = "cat-landmarks-project/processed/features/v2/"
s3_key = f"{fe_s3_prefix}image_features.parquet"

s3.upload_file(str(fe_path), bucket, s3_key)
features_location = f"s3://{bucket}/{fe_s3_prefix}"

In [13]:
# Comment: Reset table to avoid schema/location confusion
cursor.execute(f"DROP TABLE IF EXISTS {database_name}.image_landmarks_features")

In [14]:
# Registering Athena table for engineered features

features_location = f"s3://{bucket}/{fe_s3_prefix}"

create_features_table = f"""
CREATE EXTERNAL TABLE IF NOT EXISTS {database_name}.image_landmarks_features (
    image_id          STRING,
    label             BIGINT,
    file_size         BIGINT,
    width             INT,
    height            INT,
    aspect_ratio      DOUBLE,
    area              BIGINT,
    log_file_size     DOUBLE,
    eye_center_x_norm DOUBLE,
    eye_center_y_norm DOUBLE,
    eye_dist_norm     DOUBLE,
    eye_y_diff_norm   DOUBLE,
    eye_angle         DOUBLE,
    mouth_x_norm      DOUBLE,
    mouth_y_norm      DOUBLE,
    mouth_eye_y_norm  DOUBLE,
    resolution_bucket STRING,
    event_time        STRING,
    dataset_split     STRING
    
    
)
STORED AS PARQUET
LOCATION '{features_location}'
"""

cursor.execute(create_features_table)

In [15]:
statement = "SHOW TABLES in {}".format(database_name)

df_show = pd.read_sql(statement, conn)
df_show.head(5)

/tmp/ipykernel_53371/2201015668.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_show = pd.read_sql(statement, conn)

                   tab_name
0            image_combined
1  image_landmarks_features
2                 landmarks

## Feature Store

In [18]:
boto_session = boto3.Session(region_name=region)

sagemaker_client = boto_session.client(service_name="sagemaker", region_name=region)
featurestore_runtime = boto_session.client(
    service_name="sagemaker-featurestore-runtime", region_name=region
)

feature_store_session = Session(
    boto_session=boto_session,
    sagemaker_client=sagemaker_client,
    sagemaker_featurestore_runtime_client=featurestore_runtime,
)

In [19]:
prefix = "cat-landmarks-project/feature-store"

In [20]:
database_name = "cat_image_analysis"
table_name = "image_landmarks_features"

In [21]:
# -----------------------------------------
# Load engineered features from Athena table
# -----------------------------------------
query = f"""
SELECT
image_id,
label,
file_size,
width,
height,
aspect_ratio,
area,
log_file_size,
eye_center_x_norm,
eye_center_y_norm,
eye_dist_norm,
eye_y_diff_norm,
eye_angle,
mouth_x_norm,
mouth_y_norm,
mouth_eye_y_norm,
resolution_bucket,
event_time,
dataset_split
FROM {database_name}.{table_name}
"""

df_catlm_fs = pd.read_sql(query, conn)

df_catlm_fs["event_time"] = df_catlm_fs["event_time"].astype("float64")

df_catlm_fs.head(5)

/tmp/ipykernel_53371/1780845838.py:28: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_catlm_fs = pd.read_sql(query, conn)

,image_id,label,file_size,width,height,aspect_ratio,area,log_file_size,eye_center_x_norm,eye_center_y_norm,eye_dist_norm,eye_y_diff_norm,eye_angle,mouth_x_norm,mouth_y_norm,mouth_eye_y_norm,resolution_bucket,event_time,dataset_split
0,s3://sagemaker-us-east-1-567266240490/cat-land...,1,469801,375,500,0.750000,187500,13.060067,0.552,0.322000,0.170667,0.004000,0.031240,0.530667,0.398000,0.076000,None,1.770530e+09,train
1,s3://sagemaker-us-east-1-567266240490/cat-land...,1,469801,500,375,1.333333,187500,13.060067,0.249,0.297333,0.114000,0.082667,0.498117,0.206000,0.389333,0.092000,None,1.770530e+09,prod
2,s3://sagemaker-us-east-1-567266240490/cat-land...,1,469801,500,375,1.333333,187500,13.060067,0.658,0.594667,0.044000,0.005333,0.090660,0.654000,0.634667,0.040000,None,1.770530e+09,prod
3,s3://sagemaker-us-east-1-567266240490/cat-land...,1,310372,500,375,1.333333,187500,12.645530,0.409,0.477333,0.150000,0.032000,0.158655,0.382000,0.658667,0.181333,None,1.770530e+09,test
4,s3://sagemaker-us-east-1-567266240490/cat-land...,1,310372,500,333,1.501502,166500,12.645530,0.294,0.364865,0.128000,0.003003,-0.015624,0.266000,0.507508,0.142643,None,1.770530e+09,train

## Ingest Data into FeatureStore

In [22]:
df_catlm_fs.count()

image_id             24997
label                24997
file_size            24997
width                24997
height               24997
aspect_ratio         24997
area                 24997
log_file_size        24997
eye_center_x_norm     9997
eye_center_y_norm     9997
eye_dist_norm         9997
eye_y_diff_norm       9997
eye_angle             9997
mouth_x_norm          9997
mouth_y_norm          9997
mouth_eye_y_norm      9997
resolution_bucket        0
event_time           24997
dataset_split        24997
dtype: int64

In [23]:
combined_landmark_feature_group_name = "combined-landmark-feature-group-" + strftime("%d-%H-%M-%S", gmtime())

In [24]:
combined_landmark_feature_group = FeatureGroup(
    name=combined_landmark_feature_group_name, sagemaker_session=feature_store_session
)

In [25]:
current_time_sec = int(round(time.time()))

def cast_object_to_string(data_frame):
    for label in data_frame.columns:
        if data_frame.dtypes[label] == "object":
            data_frame[label] = data_frame[label].astype("str").astype("string")


record_identifier_feature_name = "image_id"
event_time_feature_name = "event_time"

# ---- sanity checks (do these once)
if record_identifier_feature_name not in df_catlm_fs.columns:
    raise ValueError("image_id is missing. Create it before Feature Store ingestion.")

if df_catlm_fs[record_identifier_feature_name].isna().any():
    raise ValueError("image_id contains nulls. Feature Store record identifier cannot be null.")

if not df_catlm_fs[record_identifier_feature_name].is_unique:
    raise ValueError("image_id must be unique. You have duplicates (would overwrite records).")

# ---- cast object dtype -> pandas string dtype
cast_object_to_string(df_catlm_fs)

# ---- load feature definitions (schema inference)
combined_landmark_feature_group.load_feature_definitions(data_frame=df_catlm_fs)

[FeatureDefinition(feature_name='image_id', feature_type=<FeatureTypeEnum.STRING: 'String'>, collection_type=None),
 FeatureDefinition(feature_name='label', feature_type=<FeatureTypeEnum.INTEGRAL: 'Integral'>, collection_type=None),
 FeatureDefinition(feature_name='file_size', feature_type=<FeatureTypeEnum.INTEGRAL: 'Integral'>, collection_type=None),
 FeatureDefinition(feature_name='width', feature_type=<FeatureTypeEnum.INTEGRAL: 'Integral'>, collection_type=None),
 FeatureDefinition(feature_name='height', feature_type=<FeatureTypeEnum.INTEGRAL: 'Integral'>, collection_type=None),
 FeatureDefinition(feature_name='aspect_ratio', feature_type=<FeatureTypeEnum.FRACTIONAL: 'Fractional'>, collection_type=None),
 FeatureDefinition(feature_name='area', feature_type=<FeatureTypeEnum.INTEGRAL: 'Integral'>, collection_type=None),
 FeatureDefinition(feature_name='log_file_size', feature_type=<FeatureTypeEnum.FRACTIONAL: 'Fractional'>, collection_type=None),
 FeatureDefinition(feature_name='eye_center_x_norm', feature_type=<FeatureTypeEnum.FRACTIONAL: 'Fractional'>, collection_type=None),
 FeatureDefinition(feature_name='eye_center_y_norm', feature_type=<FeatureTypeEnum.FRACTIONAL: 'Fractional'>, collection_type=None),
 FeatureDefinition(feature_name='eye_dist_norm', feature_type=<FeatureTypeEnum.FRACTIONAL: 'Fractional'>, collection_type=None),
 FeatureDefinition(feature_name='eye_y_diff_norm', feature_type=<FeatureTypeEnum.FRACTIONAL: 'Fractional'>, collection_type=None),
 FeatureDefinition(feature_name='eye_angle', feature_type=<FeatureTypeEnum.FRACTIONAL: 'Fractional'>, collection_type=None),
 FeatureDefinition(feature_name='mouth_x_norm', feature_type=<FeatureTypeEnum.FRACTIONAL: 'Fractional'>, collection_type=None),
 FeatureDefinition(feature_name='mouth_y_norm', feature_type=<FeatureTypeEnum.FRACTIONAL: 'Fractional'>, collection_type=None),
 FeatureDefinition(feature_name='mouth_eye_y_norm', feature_type=<FeatureTypeEnum.FRACTIONAL: 'Fractional'>, collection_type=None),
 FeatureDefinition(feature_name='resolution_bucket', feature_type=<FeatureTypeEnum.STRING: 'String'>, collection_type=None),
 FeatureDefinition(feature_name='event_time', feature_type=<FeatureTypeEnum.FRACTIONAL: 'Fractional'>, collection_type=None),
 FeatureDefinition(feature_name='dataset_split', feature_type=<FeatureTypeEnum.STRING: 'String'>, collection_type=None)]

In [26]:
df_catlm_fs["event_time"].dtype
df_catlm_fs["event_time"].head()

0    1.770530e+09
1    1.770530e+09
2    1.770530e+09
3    1.770530e+09
4    1.770530e+09
Name: event_time, dtype: float64

In [27]:
df_catlm_fs.count()

image_id             24997
label                24997
file_size            24997
width                24997
height               24997
aspect_ratio         24997
area                 24997
log_file_size        24997
eye_center_x_norm     9997
eye_center_y_norm     9997
eye_dist_norm         9997
eye_y_diff_norm       9997
eye_angle             9997
mouth_x_norm          9997
mouth_y_norm          9997
mouth_eye_y_norm      9997
resolution_bucket    24997
event_time           24997
dataset_split        24997
dtype: int64

In [28]:
def wait_for_feature_group_creation_complete(feature_group):
    status = feature_group.describe().get("FeatureGroupStatus")
    while status == "Creating":
        print("Waiting for Feature Group Creation")
        time.sleep(5)
        status = feature_group.describe().get("FeatureGroupStatus")
    if status != "Created":
        raise RuntimeError(f"Failed to create feature group {feature_group.name}")
    print(f"FeatureGroup {feature_group.name} successfully created.")


combined_landmark_feature_group.create(
    s3_uri=f"s3://{bucket}/{prefix}",
    record_identifier_name=record_identifier_feature_name,
    event_time_feature_name=event_time_feature_name,
    role_arn=role,
    enable_online_store=True,
)


wait_for_feature_group_creation_complete(feature_group=combined_landmark_feature_group)

Waiting for Feature Group Creation
Waiting for Feature Group Creation
Waiting for Feature Group Creation
Waiting for Feature Group Creation
Waiting for Feature Group Creation
Waiting for Feature Group Creation
Waiting for Feature Group Creation
Waiting for Feature Group Creation
Waiting for Feature Group Creation
Waiting for Feature Group Creation
Waiting for Feature Group Creation
FeatureGroup combined-landmark-feature-group-08-05-48-54 successfully created.

In [29]:
combined_landmark_feature_group.describe()

{'FeatureGroupArn': 'arn:aws:sagemaker:us-east-1:567266240490:feature-group/combined-landmark-feature-group-08-05-48-54',
 'FeatureGroupName': 'combined-landmark-feature-group-08-05-48-54',
 'RecordIdentifierFeatureName': 'image_id',
 'EventTimeFeatureName': 'event_time',
 'FeatureDefinitions': [{'FeatureName': 'image_id', 'FeatureType': 'String'},
  {'FeatureName': 'label', 'FeatureType': 'Integral'},
  {'FeatureName': 'file_size', 'FeatureType': 'Integral'},
  {'FeatureName': 'width', 'FeatureType': 'Integral'},
  {'FeatureName': 'height', 'FeatureType': 'Integral'},
  {'FeatureName': 'aspect_ratio', 'FeatureType': 'Fractional'},
  {'FeatureName': 'area', 'FeatureType': 'Integral'},
  {'FeatureName': 'log_file_size', 'FeatureType': 'Fractional'},
  {'FeatureName': 'eye_center_x_norm', 'FeatureType': 'Fractional'},
  {'FeatureName': 'eye_center_y_norm', 'FeatureType': 'Fractional'},
  {'FeatureName': 'eye_dist_norm', 'FeatureType': 'Fractional'},
  {'FeatureName': 'eye_y_diff_norm', 'FeatureType': 'Fractional'},
  {'FeatureName': 'eye_angle', 'FeatureType': 'Fractional'},
  {'FeatureName': 'mouth_x_norm', 'FeatureType': 'Fractional'},
  {'FeatureName': 'mouth_y_norm', 'FeatureType': 'Fractional'},
  {'FeatureName': 'mouth_eye_y_norm', 'FeatureType': 'Fractional'},
  {'FeatureName': 'resolution_bucket', 'FeatureType': 'String'},
  {'FeatureName': 'event_time', 'FeatureType': 'Fractional'},
  {'FeatureName': 'dataset_split', 'FeatureType': 'String'}],
 'CreationTime': datetime.datetime(2026, 2, 8, 5, 49, 32, 914000, tzinfo=tzlocal()),
 'OnlineStoreConfig': {'EnableOnlineStore': True},
 'OfflineStoreConfig': {'S3StorageConfig': {'S3Uri': 's3://sagemaker-us-east-1-567266240490/cat-landmarks-project/feature-store',
   'ResolvedOutputS3Uri': 's3://sagemaker-us-east-1-567266240490/cat-landmarks-project/feature-store/567266240490/sagemaker/us-east-1/offline-store/combined-landmark-feature-group-08-05-48-54-1770529772/data'},
  'DisableGlueTableCreation': False,
  'DataCatalogConfig': {'TableName': 'combined_landmark_feature_group_08_05_48_54_1770529772',
   'Catalog': 'AwsDataCatalog',
   'Database': 'sagemaker_featurestore'}},
 'ThroughputConfig': {'ThroughputMode': 'OnDemand'},
 'RoleArn': 'arn:aws:iam::567266240490:role/LabRole',
 'FeatureGroupStatus': 'Created',
 'OnlineStoreTotalSizeBytes': 0,
 'ResponseMetadata': {'RequestId': '05198a74-9122-4ad9-90e7-7f0d7bc5cabb',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amzn-requestid': '05198a74-9122-4ad9-90e7-7f0d7bc5cabb',
   'strict-transport-security': 'max-age=47304000; includeSubDomains',
   'x-frame-options': 'DENY',
   'content-security-policy': "frame-ancestors 'none'",
   'cache-control': 'no-cache, no-store, must-revalidate',
   'x-content-type-options': 'nosniff',
   'content-type': 'application/x-amz-json-1.1',
   'content-length': '2596',
   'date': 'Sun, 08 Feb 2026 05:51:21 GMT'},
  'RetryAttempts': 0}}

In [30]:
combined_landmark_feature_group.ingest(data_frame=df_catlm_fs, max_workers=3, wait=True)

IngestionManagerPandas(feature_group_name='combined-landmark-feature-group-08-05-48-54', feature_definitions={'image_id': {'FeatureName': 'image_id', 'FeatureType': 'String'}, 'label': {'FeatureName': 'label', 'FeatureType': 'Integral'}, 'file_size': {'FeatureName': 'file_size', 'FeatureType': 'Integral'}, 'width': {'FeatureName': 'width', 'FeatureType': 'Integral'}, 'height': {'FeatureName': 'height', 'FeatureType': 'Integral'}, 'aspect_ratio': {'FeatureName': 'aspect_ratio', 'FeatureType': 'Fractional'}, 'area': {'FeatureName': 'area', 'FeatureType': 'Integral'}, 'log_file_size': {'FeatureName': 'log_file_size', 'FeatureType': 'Fractional'}, 'eye_center_x_norm': {'FeatureName': 'eye_center_x_norm', 'FeatureType': 'Fractional'}, 'eye_center_y_norm': {'FeatureName': 'eye_center_y_norm', 'FeatureType': 'Fractional'}, 'eye_dist_norm': {'FeatureName': 'eye_dist_norm', 'FeatureType': 'Fractional'}, 'eye_y_diff_norm': {'FeatureName': 'eye_y_diff_norm', 'FeatureType': 'Fractional'}, 'eye_angle': {'FeatureName': 'eye_angle', 'FeatureType': 'Fractional'}, 'mouth_x_norm': {'FeatureName': 'mouth_x_norm', 'FeatureType': 'Fractional'}, 'mouth_y_norm': {'FeatureName': 'mouth_y_norm', 'FeatureType': 'Fractional'}, 'mouth_eye_y_norm': {'FeatureName': 'mouth_eye_y_norm', 'FeatureType': 'Fractional'}, 'resolution_bucket': {'FeatureName': 'resolution_bucket', 'FeatureType': 'String'}, 'event_time': {'FeatureName': 'event_time', 'FeatureType': 'Fractional'}, 'dataset_split': {'FeatureName': 'dataset_split', 'FeatureType': 'String'}}, sagemaker_fs_runtime_client_config=<botocore.config.Config object at 0x7f0cbb1babd0>, sagemaker_session=<sagemaker.session.Session object at 0x7f0cd41bbc50>, max_workers=3, max_processes=1, profile_name=None, _async_result=<multiprocess.pool.MapResult object at 0x7f0cdc1bfbc0>, _processing_pool=<pool ProcessPool(ncpus=1)>, _failed_indices=[])

In [31]:
#  Verifying
record_identifier_value = f"s3://{bucket}/cat-landmarks-project/raw/cats/images/CAT_00/00000001_000.jpg"

fg_name = combined_landmark_feature_group.name  

response = featurestore_runtime.get_record(
    FeatureGroupName=fg_name,
    RecordIdentifierValueAsString=record_identifier_value,
)

print(response["Record"])

[{'FeatureName': 'image_id', 'ValueAsString': 's3://sagemaker-us-east-1-567266240490/cat-landmarks-project/raw/cats/images/CAT_00/00000001_000.jpg'}, {'FeatureName': 'label', 'ValueAsString': '1'}, {'FeatureName': 'file_size', 'ValueAsString': '469801'}, {'FeatureName': 'width', 'ValueAsString': '375'}, {'FeatureName': 'height', 'ValueAsString': '500'}, {'FeatureName': 'aspect_ratio', 'ValueAsString': '0.75'}, {'FeatureName': 'area', 'ValueAsString': '187500'}, {'FeatureName': 'log_file_size', 'ValueAsString': '13.060066608328581'}, {'FeatureName': 'eye_center_x_norm', 'ValueAsString': '0.552'}, {'FeatureName': 'eye_center_y_norm', 'ValueAsString': '0.322'}, {'FeatureName': 'eye_dist_norm', 'ValueAsString': '0.17066666666666666'}, {'FeatureName': 'eye_y_diff_norm', 'ValueAsString': '0.0040000000000000036'}, {'FeatureName': 'eye_angle', 'ValueAsString': '0.031239833430268277'}, {'FeatureName': 'mouth_x_norm', 'ValueAsString': '0.5306666666666666'}, {'FeatureName': 'mouth_y_norm', 'ValueAsString': '0.398'}, {'FeatureName': 'mouth_eye_y_norm', 'ValueAsString': '0.07600000000000001'}, {'FeatureName': 'resolution_bucket', 'ValueAsString': 'None'}, {'FeatureName': 'event_time', 'ValueAsString': '1770529590.068841'}, {'FeatureName': 'dataset_split', 'ValueAsString': 'train'}]

## Data Prepocessing

### Data  Resizing,  Augmentation and Normalization
#### Augmentation is applied on-the-fly only to positive samples (label=1) during training, while resizing and normalization are applied to all samples to ensure consistent input shape and scale

In [34]:
def read_image_from_s3(s3_uri: str) -> Image.Image:
    bucket, key = s3_uri.replace("s3://", "").split("/", 1)
    obj = s3.get_object(Bucket=bucket, Key=key)
    return Image.open(io.BytesIO(obj["Body"].read())).convert("RGB")

In [35]:
combined_landmark_feature_group = FeatureGroup(
    name= combined_landmark_feature_group_name,
    sagemaker_session=sess
)

desc = combined_landmark_feature_group.describe()
print(desc["FeatureGroupStatus"])

Created

In [36]:
# Comments:
# - Lists existing Feature Groups in your account/region
# - Helps you find the exact FeatureGroupName string to use

sm = boto3.client("sagemaker")

resp = sm.list_feature_groups(MaxResults=50)
for fg in resp["FeatureGroupSummaries"]:
    print(fg["FeatureGroupName"])

housing-enriched-feature-group-27-03-39-45_1
housing-enriched-feature-group-27-02-55-40_1
housing-enriched-feature-group-27-02-46-58
combined-landmark-feature-group-08-05-48-54
combined-landmark-feature-group-08-05-22-07

In [37]:
offline_cfg = desc.get("OfflineStoreConfig", {})
print(offline_cfg)

{'S3StorageConfig': {'S3Uri': 's3://sagemaker-us-east-1-567266240490/cat-landmarks-project/feature-store', 'ResolvedOutputS3Uri': 's3://sagemaker-us-east-1-567266240490/cat-landmarks-project/feature-store/567266240490/sagemaker/us-east-1/offline-store/combined-landmark-feature-group-08-05-48-54-1770529772/data'}, 'DisableGlueTableCreation': False, 'DataCatalogConfig': {'TableName': 'combined_landmark_feature_group_08_05_48_54_1770529772', 'Catalog': 'AwsDataCatalog', 'Database': 'sagemaker_featurestore'}}

In [39]:
combined_query = combined_landmark_feature_group.athena_query()

query_string = """
SELECT *
FROM "{db}"."{table}"
WHERE dataset_split = 'test'
""".format(
    db=combined_query.database,
    table=combined_query.table_name
)


print("Running " + query_string)


combined_query.run(
    query_string=query_string,
    output_location = f"s3://{bucket}/athena-results/"

)

print("Running:\n", query_string)

# run Athena query. The output is loaded to a Pandas dataframe.
# dataset = pd.DataFrame()
combined_query.run(
    query_string=query_string,
    output_location="s3://" + bucket + "/" + prefix + "/query_results/",
)
combined_query.wait()
dataset_test= combined_query.as_dataframe()

dataset_test.head(3)

Running
SELECT *
FROM "sagemaker_featurestore"."combined_landmark_feature_group_08_05_48_54_1770529772"
WHERE dataset_split = 'test'

Running:

SELECT *
FROM "sagemaker_featurestore"."combined_landmark_feature_group_08_05_48_54_1770529772"
WHERE dataset_split = 'test'

,image_id,label,file_size,width,height,aspect_ratio,area,log_file_size,eye_center_x_norm,eye_center_y_norm,...,eye_angle,mouth_x_norm,mouth_y_norm,mouth_eye_y_norm,resolution_bucket,event_time,dataset_split,write_time,api_invocation_time,is_deleted
0,s3://sagemaker-us-east-1-567266240490/cat-land...,0,2332,32,32,1.000000,1024,7.754910,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.770530e+09,test,2026-02-08 05:56:22.520,2026-02-08 05:51:28.000,False
1,s3://sagemaker-us-east-1-567266240490/cat-land...,1,85100,500,295,1.694915,147500,11.351594,0.358000,0.350847,...,-0.078784,0.328000,0.454237,0.103390,NaN,1.770530e+09,test,2026-02-08 05:56:22.520,2026-02-08 05:51:28.000,False
2,s3://sagemaker-us-east-1-567266240490/cat-land...,1,396050,1024,683,1.499268,699392,12.889298,0.395508,0.545388,...,-0.088007,0.400391,0.825769,0.280381,NaN,1.770530e+09,test,2026-02-08 05:56:22.520,2026-02-08 05:51:30.000,False

In [40]:
# Inspect the actual distinct values (and NULLs)
query_string = f"""
SELECT dataset_split, count(*) AS n
FROM "{combined_query.database}"."{combined_query.table_name}"
GROUP BY dataset_split
ORDER BY n DESC
"""
combined_query.run(query_string=query_string, output_location=f"s3://{bucket}/athena-results/")
combined_query.wait()
combined_query.as_dataframe()

  dataset_split      n
0          prod  10015
1         train   9913
2          test   2544
3           val   2525

In [41]:
combined_query = combined_landmark_feature_group.athena_query()

query_string = """
SELECT *
FROM "{db}"."{table}"
WHERE dataset_split = 'val'
""".format(
    db=combined_query.database,
    table=combined_query.table_name
)


print("Running " + query_string)


combined_query.run(
    query_string=query_string,
    output_location = f"s3://{bucket}/athena-results/"

)

print("Running:\n", query_string)

# run Athena query. The output is loaded to a Pandas dataframe.
# dataset = pd.DataFrame()
combined_query.run(
    query_string=query_string,
    output_location="s3://" + bucket + "/" + prefix + "/query_results/",
)
combined_query.wait()
dataset_val = combined_query.as_dataframe()

dataset_val.head(3)

Running
SELECT *
FROM "sagemaker_featurestore"."combined_landmark_feature_group_08_05_48_54_1770529772"
WHERE dataset_split = 'val'

Running:

SELECT *
FROM "sagemaker_featurestore"."combined_landmark_feature_group_08_05_48_54_1770529772"
WHERE dataset_split = 'val'

,image_id,label,file_size,width,height,aspect_ratio,area,log_file_size,eye_center_x_norm,eye_center_y_norm,...,eye_angle,mouth_x_norm,mouth_y_norm,mouth_eye_y_norm,resolution_bucket,event_time,dataset_split,write_time,api_invocation_time,is_deleted
0,s3://sagemaker-us-east-1-567266240490/cat-land...,1,126317,375,500,0.750000,187500,11.746558,0.488000,0.332000,...,0.463648,0.450667,0.394000,0.062000,NaN,1.770530e+09,val,2026-02-08 05:56:28.297,2026-02-08 05:51:29.000,False
1,s3://sagemaker-us-east-1-567266240490/cat-land...,1,428013,768,1024,0.750000,786432,12.966911,0.323568,0.420898,...,-0.050378,0.329427,0.512695,0.091797,NaN,1.770530e+09,val,2026-02-08 05:56:28.297,2026-02-08 05:51:33.000,False
2,s3://sagemaker-us-east-1-567266240490/cat-land...,1,343184,1024,683,1.499268,699392,12.746025,0.501465,0.464861,...,0.305448,0.454102,0.588580,0.123719,NaN,1.770530e+09,val,2026-02-08 05:56:28.297,2026-02-08 05:51:35.000,False

In [43]:
combined_query = combined_landmark_feature_group.athena_query()

query_string = """
SELECT *
FROM "{db}"."{table}"
WHERE dataset_split = 'train'
""".format(
    db=combined_query.database,
    table=combined_query.table_name
)


print("Running " + query_string)


combined_query.run(
    query_string=query_string,
    output_location = f"s3://{bucket}/athena-results/"

)

print("Running:\n", query_string)

# run Athena query. The output is loaded to a Pandas dataframe.
# dataset = pd.DataFrame()
combined_query.run(
    query_string=query_string,
    output_location="s3://" + bucket + "/" + prefix + "/query_results/",
)
combined_query.wait()
dataset_train = combined_query.as_dataframe()

dataset_train.head(3)

Running
SELECT *
FROM "sagemaker_featurestore"."combined_landmark_feature_group_08_05_48_54_1770529772"
WHERE dataset_split = 'train'

Running:

SELECT *
FROM "sagemaker_featurestore"."combined_landmark_feature_group_08_05_48_54_1770529772"
WHERE dataset_split = 'train'

,image_id,label,file_size,width,height,aspect_ratio,area,log_file_size,eye_center_x_norm,eye_center_y_norm,...,eye_angle,mouth_x_norm,mouth_y_norm,mouth_eye_y_norm,resolution_bucket,event_time,dataset_split,write_time,api_invocation_time,is_deleted
0,s3://sagemaker-us-east-1-567266240490/cat-land...,1,364942,500,340,1.470588,170000,12.807496,0.686000,0.575000,...,-0.014285,0.686000,0.723529,0.148529,NaN,1.770530e+09,train,2026-02-08 05:56:27.320,2026-02-08 05:51:28.000,False
1,s3://sagemaker-us-east-1-567266240490/cat-land...,0,2409,32,32,1.000000,1024,7.787382,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.770530e+09,train,2026-02-08 05:56:27.320,2026-02-08 05:51:28.000,False
2,s3://sagemaker-us-east-1-567266240490/cat-land...,1,467715,1024,682,1.501466,698368,13.055617,0.529785,0.334311,...,0.207496,0.513672,0.444282,0.109971,NaN,1.770530e+09,train,2026-02-08 05:56:27.320,2026-02-08 05:51:28.000,False

In [42]:
# Comments:
# - Uses s3_uri ie image_id to load image
# - Augment only cat images (label==1) during training
# - Resize for ALL images so shapes match
# - Normalize for ALL images

import numpy as np
from PIL import Image

def resize_image(image_np, size=(224, 224)):
    return np.array(Image.fromarray(image_np).resize(size, Image.BILINEAR))

class CatClsDataset:
    def __init__(self, df, augment=False, aug=None, image_size=(224, 224)):
        self.df = df.reset_index(drop=True)
        self.augment = augment
        self.aug = aug
        self.image_size = image_size

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        label = int(row["label"])

        img_np = np.array(read_image_from_s3(row["image_id"]))

        # augment only for cat images
        if self.augment and label == 1 and self.aug is not None:
            img_np = self.aug(image=img_np)["image"]

        # resize for all images (label 0 and 1)
        img_np = resize_image(img_np, size=self.image_size)

        # normalize for all images
        img_np = img_np.astype(np.float32) / 255.0

        return img_np, label

In [46]:
# Augmentation applies ONLY to cat images (label == 1)
cat_aug = A.Compose(
    [
        A.HorizontalFlip(p=0.5),
        A.ShiftScaleRotate(
            shift_limit=0.05,
            scale_limit=0.10,
            rotate_limit=15,
            p=0.7
        ),
        A.RandomBrightnessContrast(p=0.4),
    ],
    keypoint_params=A.KeypointParams(format="xy", remove_invisible=True)
)

def augment_cat_only(image_np, keypoints_xy):
    out = cat_aug(image=image_np, keypoints=keypoints_xy)
    return out["image"], out["keypoints"]

/opt/conda/lib/python3.12/site-packages/albumentations/core/validation.py:114: UserWarning: ShiftScaleRotate is a special case of Affine transform. Please use Affine transform instead.
  original_init(self, **validated_kwargs)

In [47]:
train_ds = CatClsDataset(dataset_train, augment=True,  aug=cat_aug, image_size=(224, 224))
val_ds   = CatClsDataset(dataset_val,   augment=False, aug=None,   image_size=(224, 224))
test_ds  = CatClsDataset(dataset_test,  augment=False, aug=None,   image_size=(224, 224))

###  Verifying if Resizing worked

In [48]:
img_cat, y_cat = train_ds[dataset_train[dataset_train["label"]==1].index[0]]
img_nc,  y_nc  = train_ds[dataset_train[dataset_train["label"]==0].index[0]]

print(y_cat, img_cat.shape)
print(y_nc,  img_nc.shape)

1 (224, 224, 3)
0 (224, 224, 3)

### Verifying if Augemntation worked

In [49]:
cat_idx = dataset_train[dataset_train["label"]==1].index[0]
img1, y1 = train_ds[cat_idx]
img2, y2 = train_ds[cat_idx]
print("cat diff:", np.mean(np.abs(img1 - img2)))

noncat_idx = dataset_train[dataset_train["label"]==0].index[0]
img1, y1 = train_ds[noncat_idx]
img2, y2 = train_ds[noncat_idx]
print("noncat diff:", np.mean(np.abs(img1 - img2)))

cat diff: 0.15810771
noncat diff: 0.0

In [50]:
# Comments:
# - Creates small manifest files that point to image locations + labels
# - These CSVs are NOT the images; they just index them
local_dir = "/tmp/cat_manifests"
os.makedirs(local_dir, exist_ok=True)

def write_manifest(df, out_path):
    df[["image_id", "label"]].to_csv(out_path, index=False)

write_manifest(dataset_train, f"{local_dir}/train.csv")
write_manifest(dataset_val,   f"{local_dir}/val.csv")
write_manifest(dataset_test,  f"{local_dir}/test.csv")

print("Wrote:", os.listdir(local_dir))

Wrote: ['train.csv', 'val.csv', 'test.csv']

In [56]:
manifest_dir = "cat-landmarks-project/feature-store/manifests"

In [51]:

#  Uploading manifest CSVs to S3 so SageMaker training job can download them
s3.upload_file(f"{local_dir}/train.csv", bucket, f"{manifest_dir}/train/train.csv")
s3.upload_file(f"{local_dir}/val.csv",   bucket, f"{manifest_dir}/val/val.csv")
s3.upload_file(f"{local_dir}/test.csv",  bucket, f"{manifest_dir}/test/test.csv")

print("Uploaded manifests.")

Uploaded manifests.

## Modelling

In [57]:
training_output_path = f"s3://{bucket}/{prefix}/training_output"

training_model = PyTorch(
    entry_point="train.py",        
    source_dir="src",              
    role=role,
    framework_version="2.1",
    py_version="py310",
    instance_count=1,
    instance_type="ml.m5.large",  
    output_path=training_output_path,
    hyperparameters={
        "epochs": 2,
        "batch_size": 32,
        "lr": 1e-3,
        "image_size": 224
    },
)

In [ ]:
inputs = {
    "train": f"s3://{bucket}/{manifest_dir}/train/",
    "val":   f"s3://{bucket}/{manifest_dir}/val/",
}
training_model.fit(inputs=inputs, logs=True)

INFO:sagemaker.telemetry.telemetry_logging:SageMaker Python SDK will collect telemetry to help us better understand our user's needs, diagnose issues, and deliver additional features.
To opt out of telemetry, please disable via TelemetryOptOut parameter in SDK defaults config. For more information, refer to https://sagemaker.readthedocs.io/en/stable/overview.html#configuring-and-using-defaults-with-the-sagemaker-python-sdk.
INFO:sagemaker.image_uris:image_uri is not presented, retrieving image_uri based on instance_type, framework etc.
INFO:sagemaker.image_uris:image_uri is not presented, retrieving image_uri based on instance_type, framework etc.
INFO:sagemaker:Creating training-job with name: pytorch-training-2026-02-08-06-21-02-268

2026-02-08 06:21:03 Starting - Starting the training job...
2026-02-08 06:21:18 Starting - Preparing the instances for training...
2026-02-08 06:21:40 Downloading - Downloading input data...
2026-02-08 06:22:26 Downloading - Downloading the training image........
2026-02-08 06:23:49 Training - Training image download completed. Training in progress.bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
/opt/conda/lib/python3.10/site-packages/paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
/opt/conda/lib/python3.10/site-packages/paramiko/transport.py:259: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,
2026-02-08 06:23:53,297 sagemaker-training-toolkit INFO     Imported framework sagemaker_pytorch_container.training
2026-02-08 06:23:53,298 sagemaker-training-toolkit INFO     No GPUs detected (normal if no gpus installed)
2026-02-08 06:23:53,298 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-02-08 06:23:53,308 sagemaker_pytorch_container.training INFO     Block until all host DNS lookups succeed.
2026-02-08 06:23:53,316 sagemaker_pytorch_container.training INFO     Invoking user training script.
2026-02-08 06:23:55,113 sagemaker-training-toolkit INFO     No GPUs detected (normal if no gpus installed)
2026-02-08 06:23:55,114 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-02-08 06:23:55,132 sagemaker-training-toolkit INFO     No GPUs detected (normal if no gpus installed)
2026-02-08 06:23:55,133 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-02-08 06:23:55,144 sagemaker-training-toolkit INFO     No GPUs detected (normal if no gpus installed)
2026-02-08 06:23:55,145 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)
2026-02-08 06:23:55,157 sagemaker-training-toolkit INFO     Invoking user script
Training Env:
{
    "additional_framework_parameters": {},
    "channel_input_dirs": {
        "train": "/opt/ml/input/data/train",
        "val": "/opt/ml/input/data/val"
    },
    "current_host": "algo-1",
    "current_instance_group": "homogeneousCluster",
    "current_instance_group_hosts": [
        "algo-1"
    ],
    "current_instance_type": "ml.m5.large",
    "distribution_hosts": [],
    "distribution_instance_groups": [],
    "framework_module": "sagemaker_pytorch_container.training:main",
    "hosts": [
        "algo-1"
    ],
    "hyperparameters": {
        "batch_size": 32,
        "epochs": 2,
        "image_size": 224,
        "lr": 0.001
    },
    "input_config_dir": "/opt/ml/input/config",
    "input_data_config": {
        "train": {
            "TrainingInputMode": "File",
            "S3DistributionType": "FullyReplicated",
            "RecordWrapperType": "None"
        },
        "val": {
            "TrainingInputMode": "File",
            "S3DistributionType": "FullyReplicated",
            "RecordWrapperType": "None"
        }
    },
    "input_dir": "/opt/ml/input",
    "instance_groups": [
        "homogeneousCluster"
    ],
    "instance_groups_dict": {
        "homogeneousCluster": {
            "instance_group_name": "homogeneousCluster",
            "instance_type": "ml.m5.large",
            "hosts": [
                "algo-1"
            ]
        }
    },
    "is_hetero": false,
    "is_master": true,
    "is_modelparallel_enabled": null,
    "is_smddpmprun_installed": false,
    "is_smddprun_installed": false,
    "job_name": "pytorch-training-2026-02-08-06-21-02-268",
    "log_level": 20,
    "master_hostname": "algo-1",
    "model_dir": "/opt/ml/model",
    "module_dir": "s3://sagemaker-us-east-1-567266240490/pytorch-training-2026-02-08-06-21-02-268/source/sourcedir.tar.gz",
    "module_name": "train",
    "network_interface_name": "eth0",
    "num_cpus": 2,
    "num_gpus": 0,
    "num_neurons": 0,
    "output_data_dir": "/opt/ml/output/data",
    "output_dir": "/opt/ml/output",
    "output_intermediate_dir": "/opt/ml/output/intermediate",
    "resource_config": {
        "current_host": "algo-1",
        "current_instance_type": "ml.m5.large",
        "current_group_name": "homogeneousCluster",
        "hosts": [
            "algo-1"
        ],
        "instance_groups": [
            {
                "instance_group_name": "homogeneousCluster",
                "instance_type": "ml.m5.large",
                "hosts": [
                    "algo-1"
                ]
            }
        ],
        "network_interface_name": "eth0",
        "topology": null
    },
    "user_entry_point": "train.py"
}
Environment variables:
SM_HOSTS=["algo-1"]
SM_NETWORK_INTERFACE_NAME=eth0
SM_HPS={"batch_size":32,"epochs":2,"image_size":224,"lr":0.001}
SM_USER_ENTRY_POINT=train.py
SM_FRAMEWORK_PARAMS={}
SM_RESOURCE_CONFIG={"current_group_name":"homogeneousCluster","current_host":"algo-1","current_instance_type":"ml.m5.large","hosts":["algo-1"],"instance_groups":[{"hosts":["algo-1"],"instance_group_name":"homogeneousCluster","instance_type":"ml.m5.large"}],"network_interface_name":"eth0","topology":null}
SM_INPUT_DATA_CONFIG={"train":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"},"val":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"}}
SM_OUTPUT_DATA_DIR=/opt/ml/output/data
SM_CHANNELS=["train","val"]
SM_CURRENT_HOST=algo-1
SM_CURRENT_INSTANCE_TYPE=ml.m5.large
SM_CURRENT_INSTANCE_GROUP=homogeneousCluster
SM_CURRENT_INSTANCE_GROUP_HOSTS=["algo-1"]
SM_INSTANCE_GROUPS=["homogeneousCluster"]
SM_INSTANCE_GROUPS_DICT={"homogeneousCluster":{"hosts":["algo-1"],"instance_group_name":"homogeneousCluster","instance_type":"ml.m5.large"}}
SM_DISTRIBUTION_INSTANCE_GROUPS=[]
SM_IS_HETERO=false
SM_MODULE_NAME=train
SM_LOG_LEVEL=20
SM_FRAMEWORK_MODULE=sagemaker_pytorch_container.training:main
SM_INPUT_DIR=/opt/ml/input
SM_INPUT_CONFIG_DIR=/opt/ml/input/config
SM_OUTPUT_DIR=/opt/ml/output
SM_NUM_CPUS=2
SM_NUM_GPUS=0
SM_NUM_NEURONS=0
SM_MODEL_DIR=/opt/ml/model
SM_MODULE_DIR=s3://sagemaker-us-east-1-567266240490/pytorch-training-2026-02-08-06-21-02-268/source/sourcedir.tar.gz
SM_TRAINING_ENV={"additional_framework_parameters":{},"channel_input_dirs":{"train":"/opt/ml/input/data/train","val":"/opt/ml/input/data/val"},"current_host":"algo-1","current_instance_group":"homogeneousCluster","current_instance_group_hosts":["algo-1"],"current_instance_type":"ml.m5.large","distribution_hosts":[],"distribution_instance_groups":[],"framework_module":"sagemaker_pytorch_container.training:main","hosts":["algo-1"],"hyperparameters":{"batch_size":32,"epochs":2,"image_size":224,"lr":0.001},"input_config_dir":"/opt/ml/input/config","input_data_config":{"train":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"},"val":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"}},"input_dir":"/opt/ml/input","instance_groups":["homogeneousCluster"],"instance_groups_dict":{"homogeneousCluster":{"hosts":["algo-1"],"instance_group_name":"homogeneousCluster","instance_type":"ml.m5.large"}},"is_hetero":false,"is_master":true,"is_modelparallel_enabled":null,"is_smddpmprun_installed":false,"is_smddprun_installed":false,"job_name":"pytorch-training-2026-02-08-06-21-02-268","log_level":20,"master_hostname":"algo-1","model_dir":"/opt/ml/model","module_dir":"s3://sagemaker-us-east-1-567266240490/pytorch-training-2026-02-08-06-21-02-268/source/sourcedir.tar.gz","module_name":"train","network_interface_name":"eth0","num_cpus":2,"num_gpus":0,"num_neurons":0,"output_data_dir":"/opt/ml/output/data","output_dir":"/opt/ml/output","output_intermediate_dir":"/opt/ml/output/intermediate","resource_config":{"current_group_name":"homogeneousCluster","current_host":"algo-1","current_instance_type":"ml.m5.large","hosts":["algo-1"],"instance_groups":[{"hosts":["algo-1"],"instance_group_name":"homogeneousCluster","instance_type":"ml.m5.large"}],"network_interface_name":"eth0","topology":null},"user_entry_point":"train.py"}
SM_USER_ARGS=["--batch_size","32","--epochs","2","--image_size","224","--lr","0.001"]
SM_OUTPUT_INTERMEDIATE_DIR=/opt/ml/output/intermediate
SM_CHANNEL_TRAIN=/opt/ml/input/data/train
SM_CHANNEL_VAL=/opt/ml/input/data/val
SM_HP_BATCH_SIZE=32
SM_HP_EPOCHS=2
SM_HP_IMAGE_SIZE=224
SM_HP_LR=0.001
PYTHONPATH=/opt/ml/code:/opt/conda/bin:/opt/conda/lib/python310.zip:/opt/conda/lib/python3.10:/opt/conda/lib/python3.10/lib-dynload:/opt/conda/lib/python3.10/site-packages
Invoking script with the following command:
/opt/conda/bin/python3.10 train.py --batch_size 32 --epochs 2 --image_size 224 --lr 0.001
2026-02-08 06:23:55,159 sagemaker-training-toolkit INFO     Exceptions not imported for SageMaker Debugger as it is not installed.
2026-02-08 06:23:55,159 sagemaker-training-toolkit INFO     Exceptions not imported for SageMaker TF as Tensorflow is not installed.
Train dir:
/opt/ml/input/data/train
Val dir:
/opt/ml/input/data/val
Model dir:
/opt/ml/model
HP:
{'epochs': 2, 'batch_size': 32, 'lr': 0.001, 'image_size': 224}
Train rows:
9913
Val rows:
2525
Device: cpu

In [ ]:
# Loading  train/val manifests from the exact S3 locations
train_df = pd.read_csv(f"s3://{bucket}/{manifest_dir}/train/train.csv")
val_df   = pd.read_csv(f"s3://{bucket}/{manifest_dir}/val/val.csv")
test_df  = pd.read_csv(f"s3://{bucket}/{manifest_dir}/test/test.csv")

print("Val class balance:")
print(val_df["label"].value_counts(dropna=False))
print(val_df["label"].value_counts(normalize=True, dropna=False))

#  checking for leakage (train vs val)
overlap_tv = set(train_df["image_id"]).intersection(set(val_df["image_id"]))
print("Train/Val overlap:", len(overlap_tv))

# checking for any overlap also ensure test is clean
overlap_tt = set(train_df["image_id"]).intersection(set(test_df["image_id"]))
overlap_vt = set(val_df["image_id"]).intersection(set(test_df["image_id"]))
print("Train/Test overlap:", len(overlap_tt))
print("Val/Test overlap:", len(overlap_vt))